remote_theme: pmarsceill/just-the-docs

# Auxiliary links for the upper right navigation.
aux_links:
  "UncertaintyQuantiification":
    - http://giusseppe-97.github.io/UncertaintyQuantiification/  
  

  
# Not a big fan of dark mode. I think the light looks better.
# color_scheme: "dark"

# You can display an image instead of the site's title like this.
# logo: "/assets/images/example-image.png"

# Footer
footer_content: "Written by Jose P. Navarro P."

# This is the title of the website
title: "UQ Galerkin Project"